# This is an example config file.
# Rename this to config.yml and add your api keys below

notion:
  api-url: "https://api.notion.com/v1/databases/"
  api-key: "your-api-key"
  version: "2022-06-28"
  database:
    shop: "your-database-id"
    tunnel: "your-database-id"
    farm: "your-database-id"

filters:
  diamond_armor: ["diamond_helmet", "diamond_chestplate", "diamond_leggings", "diamond_boots"]
  diamond_tools: ["diamond_pickaxe", "diamond_axe", "diamond_shovel", "diamond_hoe", "diamond_sword"]
  flowers: ["allium", "azure_bluet", "blue_orchid", "cornflower", "dandelion", "lily_of_the_valley", "oxeye_daisy",
            "poppy", "torch_flower", "orange_tulip", "pink_tulip", "red_tulip", "white_tulip", "wither_rose", "lilac",
            "peony", "pitcher_plant", "rose_bush", "sunflower"]
  horse_armor:          ["_horse_armor"]
  dye:                  ["_dye"]
  sherd:                ["_sherd"]
  armor_trims:          ["_trim_smithing_template"]
  stained_glass:        ["_stained_glass"]
  stained_glass_panes:  ["_stained_glass_pane"]
  wool:                 ["_wool"]
  concrete:             ["_concrete"]
  concrete_powder:      ["_concrete_powder"]
  candles:              ["_candle"]
  terracotta:           ["_terracotta"]
  glazed_terracotta:    ["_glazed_terracotta"]