notion:
  api-url: "https://api.notion.com/v1/databases/"
  api-key: "your-notion-api-key"
  version: "2022-06-28"
  database:
    shop: "your-database-id"
    tunnel: "your-database-id"
    farm: "your-database-id"
