name: DirectoryLookup
version: '1.0-SNAPSHOT'
main: io.github.branhardy.directoryLookup.DirectoryLookup
api-version: '1.21'

commands:
  shop:
    description: "Get a list of shops selling the specified item"
    usage: "/shop [item]"

permissions:
  shop:
    description: "Allows user to use /shop command"
    default: true
  admin:
    description: "Allows user to reload the plugin and manage settings"
    default: op